package com.assignment2.gui_xiang;

import java.awt.BorderLayout;
import java.awt.Font;
import java.util.List;

import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import com.assignment2.model.PurchaseOrder;
import com.assignment2.util.JsonFileUtil;

public class PurchaseOrdersWindow extends JFrame {

    public PurchaseOrdersWindow() {
        setTitle("View Purchase Orders");
        setSize(1000, 400);
        setLocationRelativeTo(null);

        JPanel mainPanel = new JPanel(new BorderLayout(10, 10));
        mainPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        String[] columnNames = {"PO ID", "PR ID", "Item ID", "Supplier ID", "Quantity", "Status", "Generated By", "Approved By"};
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        JTable table = new JTable(tableModel);
        table.setRowHeight(30);
        table.setFont(new Font("Arial", Font.PLAIN, 14));
        table.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));

        // Load purchase orders
        try {
            List<PurchaseOrder> orders = JsonFileUtil.readPurchaseOrders("resources/PurchaseOrder.txt");
            for (PurchaseOrder po : orders) {
                tableModel.addRow(new Object[]{
                    po.getPoId(),
                    po.getPrId(),
                    po.getItemId(),
                    po.getSupplierId(),
                    po.getQuantity(),
                    po.getStatus(),
                    po.getGeneratedByUserId(),
                    po.getApprovedByUserId()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading purchase orders: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        mainPanel.add(new JScrollPane(table), BorderLayout.CENTER);
        add(mainPanel);
    }
}
